name: pomopacer

services:
  mysql:
    image: mysql:8.0
    container_name: dev-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev_password
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pomopacer-network

  redis:
    image: redis:latest
    container_name: dev-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - pomopacer-network

volumes:
  mysql_data:

networks:
  pomopacer-network:
